apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-boot-kubernetes
spec:
  selector:
    matchLabels:
      app: spring-boot-kubernetes
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-boot-kubernetes
    spec:
      containers:
        - name: spring-boot-kubernetes
          image: spring-boot-kubernetes
# Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 
# The port that the container is running on in the cluster

